global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'enabledrm-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/monitoring/metrics/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'enabledrm-system'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/monitoring/metrics'
    scrape_interval: 60s
    scrape_timeout: 15s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s