"""add_soft_delete_fields_to_jobs

Revision ID: 411cc655f122
Revises: 4b6ff43c35af
Create Date: 2025-08-17 04:36:52.479476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411cc655f122'
down_revision: Union[str, None] = '4b6ff43c35af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('jobs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'deleted_at')
    op.drop_column('jobs', 'is_deleted')
    # ### end Alembic commands ###
