"""Add priority, timeout, retry_count to jobs table

Revision ID: ce98fe37e307
Revises: fe31121f9555
Create Date: 2025-08-17 05:30:56.313156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce98fe37e307'
down_revision: Union[str, None] = 'fe31121f9555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values to handle existing data
    op.add_column('jobs', sa.Column('priority', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('jobs', sa.Column('timeout', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'retry_count')
    op.drop_column('jobs', 'timeout')
    op.drop_column('jobs', 'priority')
    # ### end Alembic commands ###
