version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "8001:8000"
    environment:
      - JWT_SECRET=test-secret-key-for-auth
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3