version: '3.8'

services:
  # Universal Targets Service
  universal-targets-service:
    build: .
    container_name: universal-targets-service
    ports:
      - "3001:3001"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://targets_user:targets_password@targets-postgres:5432/targets_db
      - REDIS_URL=redis://redis:6379/4
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - JWT_SECRET_KEY=your-secret-key-here
      - ENCRYPTION_KEY=your-encryption-key-here-32-chars
      - AUTH_SERVICE_URL=http://auth-service:8000
      - USER_SERVICE_URL=http://user-service:8000
      - AUDIT_EVENTS_SERVICE_URL=http://audit-events-service:8004
    depends_on:
      - targets-postgres
      - redis
      - rabbitmq
    networks:
      - opsconductor-network
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  # PostgreSQL Database for Targets
  targets-postgres:
    image: postgres:15-alpine
    container_name: targets-postgres
    environment:
      - POSTGRES_DB=targets_db
      - POSTGRES_USER=targets_user
      - POSTGRES_PASSWORD=targets_password
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - targets_postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - opsconductor-network
    restart: unless-stopped

  # Redis (shared with other services)
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - opsconductor-network
    restart: unless-stopped

  # RabbitMQ (shared with other services)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - opsconductor-network
    restart: unless-stopped

volumes:
  targets_postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  opsconductor-network:
    driver: bridge